#!/usr/bin/env bash
set -euo pipefail
root="$(cd "$(dirname "$0")/../../.." && pwd)"
migration="$root/database/migrations/022_rbac_policy_engine.sql"
test -f "$migration"
grep -q "effective_permissions" "$migration"
grep -q "authorize_permission" "$migration"
grep -q "replace_role_permissions" "$migration"
grep -q "platform_role_permissions_manage" "$migration"
test -f "$root/packages/permissions/src/index.ts"
grep -q "PolicyDecision" "$root/packages/permissions/src/index.ts"
grep -q "inherited-role" "$root/packages/permissions/src/index.ts"
test -f "$root/apps/web/src/components/rbac/PermissionMatrix.tsx"
test -f "$root/apps/web/src/app/admin/roles/page.tsx"
test -f "$root/apps/web/src/app/api/v1/rbac/permissions/route.ts"
test -f "$root/apps/web/src/app/api/v1/rbac/roles/[roleId]/permissions/route.ts"
test -f "$root/apps/web/src/app/api/v1/rbac/members/[userId]/roles/route.ts"
grep -q "test:rbac" "$root/apps/web/package.json"
echo "RBAC policy and administration checks passed"
