import Link from 'next/link';
import {Activity,BookOpenCheck,Braces,KeyRound,Network,ShieldCheck} from 'lucide-react';
import {auditEntries,metrics,services,tenants} from './demo-foundation';
import styles from './FoundationDashboard.module.css';
export function FoundationDashboard(){return <>
 <div className={styles.hero}><div><div className="breadcrumbs">Administration / Platform Foundation</div><h1>Platform Foundation</h1><p>Production controls for identity, tenancy, access, APIs, events, auditability and service reliability.</p></div><div className={styles.actions}><Link className="button" href="/design-system"><BookOpenCheck size={17}/>Design system</Link><Link className="button buttonPrimary" href="/admin/system-health"><Activity size={17}/>System health</Link></div></div>
 <div className="grid">{metrics.map(m=><section className="card metric" key={m.label}><span>{m.label}</span><strong>{m.value}</strong><small className="muted">{m.detail}</small></section>)}</div>
 <div className="grid" style={{marginTop:16}}><section className="card span8"><h2>Core platform services</h2><div className={styles.serviceList}>{services.map(([name,status,detail])=><div className={styles.service} key={name}><strong>{name}</strong><div><i className={styles.statusDot}/>{status}</div><span>{detail}</span></div>)}</div></section><section className="card span4"><h2>Foundation controls</h2><div className={styles.links}><div className={styles.linkCard}><ShieldCheck size={20}/><strong>RBAC + RLS</strong><span>Least-privilege authorization</span></div><div className={styles.linkCard}><KeyRound size={20}/><strong>Identity</strong><span>SSO-ready session boundary</span></div><div className={styles.linkCard}><Network size={20}/><strong>Events</strong><span>Transactional outbox pattern</span></div><div className={styles.linkCard}><Braces size={20}/><strong>API v1</strong><span>Versioned REST boundary</span></div></div></section></div>
 <div className="grid" style={{marginTop:16}}><section className="card span6"><h2>Tenants</h2><div className="tableWrap"><table><thead><tr><th>Organisation</th><th>Region</th><th>Plan</th><th>Users</th><th>Status</th></tr></thead><tbody>{tenants.map(t=><tr key={t.id}><td className={styles.tenantName}>{t.name}</td><td>{t.region}</td><td>{t.plan}</td><td>{t.users}</td><td><span className="badge success">{t.status}</span></td></tr>)}</tbody></table></div></section><section className="card span6"><h2>Recent audit events</h2><div className="tableWrap"><table><thead><tr><th>Actor</th><th>Action</th><th>Resource</th><th>Time</th></tr></thead><tbody>{auditEntries.map(e=><tr key={e.id}><td>{e.actor}</td><td><code>{e.action}</code></td><td>{e.resource}</td><td>{e.occurredAt}</td></tr>)}</tbody></table></div></section></div>
 </>}
