name: Bug report
description: Report reproducible incorrect behavior
title: "bug: "
labels: [bug]
body:
  - type: textarea
    id: description
    attributes:
      label: What happened?
    validations:
      required: true
  - type: textarea
    id: reproduction
    attributes:
      label: Reproduction steps
    validations:
      required: true
  - type: input
    id: version
    attributes:
      label: Studio OS version
    validations:
      required: true
