import type {ResizeHandle,SpreadDocument,SpreadElement} from './types';
export function snap(value:number,grid:number,enabled:boolean){return enabled?Math.round(value/grid)*grid:value}
export function constrain(element:SpreadElement,doc:Pick<SpreadDocument,'widthPt'|'heightPt'>):SpreadElement{const width=Math.max(12,Math.min(element.width,doc.widthPt));const height=Math.max(12,Math.min(element.height,doc.heightPt));return {...element,width,height,x:Math.max(0,Math.min(element.x,doc.widthPt-width)),y:Math.max(0,Math.min(element.y,doc.heightPt-height))}}
export function moveElement(doc:SpreadDocument,id:string,x:number,y:number):SpreadDocument{return {...doc,elements:doc.elements.map(el=>el.id===id?constrain({...el,x:snap(x,doc.gridSizePt,doc.snapToGrid),y:snap(y,doc.gridSizePt,doc.snapToGrid)},doc):el)}}
export function resizeElement(doc:SpreadDocument,id:string,handle:ResizeHandle,dx:number,dy:number,origin:SpreadElement):SpreadDocument{let {x,y,width,height}=origin;if(handle.includes('e'))width+=dx;if(handle.includes('s'))height+=dy;if(handle.includes('w')){x+=dx;width-=dx}if(handle.includes('n')){y+=dy;height-=dy}const next=constrain({...origin,x:snap(x,doc.gridSizePt,doc.snapToGrid),y:snap(y,doc.gridSizePt,doc.snapToGrid),width:snap(Math.max(12,width),doc.gridSizePt,doc.snapToGrid),height:snap(Math.max(12,height),doc.gridSizePt,doc.snapToGrid)},doc);return {...doc,elements:doc.elements.map(el=>el.id===id?next:el)}}
export function nudgeElement(doc:SpreadDocument,id:string,dx:number,dy:number){const el=doc.elements.find(item=>item.id===id);return el?moveElement(doc,id,el.x+dx,el.y+dy):doc}
export function updateElement(doc:SpreadDocument,id:string,patch:Partial<SpreadElement>):SpreadDocument{return {...doc,elements:doc.elements.map(el=>el.id===id?constrain({...el,...patch},doc):el)}}
export function addElement(doc:SpreadDocument,element:SpreadElement):SpreadDocument{return {...doc,elements:[...doc.elements,constrain(element,doc)]}}
export function removeElement(doc:SpreadDocument,id:string):SpreadDocument{return {...doc,elements:doc.elements.filter(el=>el.id!==id)} }
export function placeAsset(doc:SpreadDocument,input:{assetId:string;assetVersionId?:string;src:string;width?:number;height?:number}):SpreadDocument{return addElement(doc,{id:crypto.randomUUID(),kind:'image',x:doc.gridSizePt*2,y:doc.gridSizePt*2,width:input.width??240,height:input.height??160,rotation:0,zIndex:doc.elements.length,assetId:input.assetId,assetVersionId:input.assetVersionId,src:input.src})}
