import {adminDb} from '@/lib/spread-manager-server';
import {requirePermission} from '@/lib/rbac/service';
import type {SessionIdentity} from '@studio-os/auth';
import type {SpreadDocument,SpreadRevision} from './types';
function map(row:any):SpreadDocument{return {id:row.id,spreadId:row.spread_id,widthPt:Number(row.width_pt),heightPt:Number(row.height_pt),bleedPt:Number(row.bleed_pt),gridSizePt:Number(row.grid_size_pt),snapToGrid:Boolean(row.snap_to_grid),version:row.version,elements:row.content?.elements??[]}}
export async function getOrCreateDocument(identity:SessionIdentity,spreadId:string){await requirePermission(identity,'spreads.editor.read');const db=adminDb();let {data,error}=await db.from('spread_documents').select('*').eq('organisation_id',identity.organisationId).eq('spread_id',spreadId).maybeSingle();if(error)throw error;if(!data){await requirePermission(identity,'spreads.editor.update');const created=await db.from('spread_documents').insert({organisation_id:identity.organisationId,spread_id:spreadId,created_by:identity.userId,updated_by:identity.userId}).select('*').single();if(created.error)throw created.error;data=created.data}return map(data)}
export async function saveDocument(identity:SessionIdentity,document:SpreadDocument,summary:string,requestId:string){await requirePermission(identity,'spreads.editor.update');const db=adminDb();const {data,error}=await db.rpc('save_spread_document',{p_document_id:document.id,p_organisation_id:identity.organisationId,p_user_id:identity.userId,p_expected_version:document.version,p_content:{elements:document.elements},p_change_summary:summary||null});if(error)throw error;const version=(data?.[0]?.version??document.version+1) as number;await Promise.all([db.from('platform_audit_events').insert({organisation_id:identity.organisationId,request_id:requestId,actor_id:identity.userId,action:'spread.document.saved',resource_type:'spread_document',resource_id:document.id,metadata:{spreadId:document.spreadId,version}}),db.from('platform_event_outbox').insert({organisation_id:identity.organisationId,event_type:'spread.document.saved',aggregate_type:'spread',aggregate_id:document.spreadId,payload:{documentId:document.id,version}})]);return {...document,version}}
export async function listRevisions(identity:SessionIdentity,spreadId:string):Promise<SpreadRevision[]>{await requirePermission(identity,'spreads.editor.history');const db=adminDb();const doc=await db.from('spread_documents').select('id').eq('organisation_id',identity.organisationId).eq('spread_id',spreadId).single();if(doc.error)throw doc.error;const result=await db.from('spread_document_revisions').select('id,version,change_summary,created_at,created_by').eq('organisation_id',identity.organisationId).eq('document_id',doc.data.id).order('version',{ascending:false}).limit(50);if(result.error)throw result.error;return (result.data??[]).map((row:any)=>({id:row.id,version:row.version,changeSummary:row.change_summary,createdAt:row.created_at,createdBy:row.created_by}))}
export async function restoreRevision(identity:SessionIdentity,spreadId:string,revisionId:string,expectedVersion:number,requestId:string){await requirePermission(identity,'spreads.editor.history.restore');const db=adminDb();const doc=await db.from('spread_documents').select('id').eq('organisation_id',identity.organisationId).eq('spread_id',spreadId).single();if(doc.error)throw doc.error;const restored=await db.rpc('restore_spread_document_revision',{p_document_id:doc.data.id,p_revision_id:revisionId,p_organisation_id:identity.organisationId,p_user_id:identity.userId,p_expected_version:expectedVersion});if(restored.error)throw restored.error;await db.from('platform_audit_events').insert({organisation_id:identity.organisationId,request_id:requestId,actor_id:identity.userId,action:'spread.document.revision_restored',resource_type:'spread_document',resource_id:doc.data.id,metadata:{spreadId,revisionId}});return getOrCreateDocument(identity,spreadId)}
