'use client';
import {useCallback,useEffect,useRef,useState} from 'react';
import type {SpreadDocument,SpreadElement} from './types';
import {addElement,moveElement,placeAsset,removeElement} from './editor-model';
import styles from './visual-spread-editor.module.css';
export function VisualSpreadEditor({spreadId}:{spreadId:string}){const [doc,setDoc]=useState<SpreadDocument|null>(null);const [selected,setSelected]=useState<string|null>(null);const [status,setStatus]=useState('Loading…');const timer=useRef<ReturnType<typeof setTimeout>|null>(null);
useEffect(()=>{fetch(`/api/v1/spreads/${spreadId}/document`).then(r=>r.json()).then(x=>{setDoc(x.data);setStatus('Saved')}).catch(()=>setStatus('Load failed'))},[spreadId]);
const persist=useCallback((next:SpreadDocument)=>{setStatus('Unsaved');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(async()=>{setStatus('Saving…');const r=await fetch(`/api/v1/spreads/${spreadId}/document`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...next,changeSummary:'Editor autosave'})});if(r.ok){const x=await r.json();setDoc(x.data);setStatus('Saved')}else setStatus(r.status===409?'Conflict—reload required':'Save failed')},700)},[spreadId]);
function update(next:SpreadDocument){setDoc(next);persist(next)}
if(!doc)return <div className={styles.loading}>{status}</div>;
function addText(){update(addElement(doc!,{id:crypto.randomUUID(),kind:'text',x:24,y:24,width:220,height:80,rotation:0,zIndex:doc!.elements.length,text:'New text frame'}))}
function addShape(){update(addElement(doc!,{id:crypto.randomUUID(),kind:'shape',x:48,y:48,width:180,height:120,rotation:0,zIndex:doc!.elements.length,fill:'#e5e7eb'}))}
function demoAsset(){update(placeAsset(doc!,{assetId:crypto.randomUUID(),src:'/placeholder-asset.svg'}))}
return <div className={styles.editor}><header className={styles.toolbar}><button onClick={addText}>Text</button><button onClick={addShape}>Shape</button><button onClick={demoAsset}>Place asset</button><label><input type="checkbox" checked={doc.snapToGrid} onChange={e=>update({...doc,snapToGrid:e.target.checked})}/> Snap</label><span aria-live="polite">{status}</span></header><div className={styles.workspace}><div className={styles.canvas} style={{aspectRatio:`${doc.widthPt}/${doc.heightPt}`,backgroundSize:`${doc.gridSizePt}px ${doc.gridSizePt}px`}}>{doc.elements.map(el=><EditorElement key={el.id} element={el} selected={selected===el.id} onSelect={()=>setSelected(el.id)} onMove={(x,y)=>update(moveElement(doc,el.id,x,y))}/>)}</div><aside className={styles.inspector}><h2>Inspector</h2>{selected?<><p>{doc.elements.find(e=>e.id===selected)?.kind} element</p><button onClick={()=>{update(removeElement(doc,selected));setSelected(null)}}>Delete</button></>:<p>Select an element.</p>}<p>Version {doc.version}</p></aside></div></div>}
function EditorElement({element,selected,onSelect,onMove}:{element:SpreadElement;selected:boolean;onSelect:()=>void;onMove:(x:number,y:number)=>void}){const start=useRef<{x:number;y:number;left:number;top:number}|null>(null);return <div role="button" tabIndex={0} aria-label={`${element.kind} element`} className={`${styles.element} ${selected?styles.selected:''}`} style={{left:element.x,top:element.y,width:element.width,height:element.height,transform:`rotate(${element.rotation}deg)`,background:element.kind==='shape'?element.fill:undefined,zIndex:element.zIndex}} onPointerDown={e=>{onSelect();start.current={x:e.clientX,y:e.clientY,left:element.x,top:element.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(start.current)onMove(start.current.left+e.clientX-start.current.x,start.current.top+e.clientY-start.current.y)}} onPointerUp={()=>{start.current=null}}>{element.kind==='text'?element.text:element.kind==='image'?<img src={element.src} alt="Placed asset"/>:null}</div>}
