'use client';
import {useCallback,useEffect,useMemo,useRef,useState} from 'react';
import type {ResizeHandle,SpreadDocument,SpreadElement,SpreadRevision} from './types';
import {addElement,moveElement,nudgeElement,placeAsset,removeElement,resizeElement,updateElement} from './editor-model';
import styles from './visual-spread-editor.module.css';
import {ReviewPanel} from '@/features/reviews/ReviewPanel';
import type {SpreadAnnotation} from '@/features/reviews/types';

type AssetRow={id:string;current_version_id?:string;title?:string;filename?:string;preview_url?:string;storage_path?:string};
const handles:ResizeHandle[]=['nw','n','ne','e','se','s','sw','w'];
export function VisualSpreadEditor({spreadId,bookId}:{spreadId:string;bookId:string}){
 const [doc,setDoc]=useState<SpreadDocument|null>(null),[selected,setSelected]=useState<string|null>(null),[status,setStatus]=useState('Loading…'),[zoom,setZoom]=useState(100),[history,setHistory]=useState<SpreadDocument[]>([]),[future,setFuture]=useState<SpreadDocument[]>([]),[revisions,setRevisions]=useState<SpreadRevision[]>([]),[assets,setAssets]=useState<AssetRow[]>([]),[showAssets,setShowAssets]=useState(false),[showHistory,setShowHistory]=useState(false),[activeAnnotation,setActiveAnnotation]=useState<SpreadAnnotation|null>(null);
 const timer=useRef<ReturnType<typeof setTimeout>|null>(null), viewport=useRef<HTMLDivElement|null>(null);
 const load=useCallback(async()=>{const r=await fetch(`/api/v1/spreads/${spreadId}/document`);const x=await r.json();if(!r.ok)throw new Error();setDoc(x.data);setStatus('Saved')},[spreadId]);
 useEffect(()=>{load().catch(()=>setStatus('Load failed'))},[load]);
 const persist=useCallback((next:SpreadDocument,summary='Editor autosave')=>{setStatus('Unsaved');if(timer.current)clearTimeout(timer.current);timer.current=setTimeout(async()=>{setStatus('Saving…');const r=await fetch(`/api/v1/spreads/${spreadId}/document`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({...next,changeSummary:summary})});if(r.ok){const x=await r.json();setDoc(x.data);setStatus('Saved')}else setStatus(r.status===409?'Conflict—reload required':'Save failed')},700)},[spreadId]);
 function update(next:SpreadDocument,record=true){if(!doc)return;if(record){setHistory(h=>[...h.slice(-49),doc]);setFuture([])}setDoc(next);persist(next)}
 function undo(){const previous=history.at(-1);if(!previous||!doc)return;setFuture(f=>[doc,...f]);setHistory(h=>h.slice(0,-1));setDoc(previous);persist(previous,'Undo')}
 function redo(){const next=future[0];if(!next||!doc)return;setHistory(h=>[...h,doc]);setFuture(f=>f.slice(1));setDoc(next);persist(next,'Redo')}
 async function openAssets(){setShowAssets(true);const r=await fetch('/api/assets/search',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({bookId,filters:{query:''}})});const x=await r.json();setAssets(x.data??x??[])}
 async function openHistory(){setShowHistory(true);const r=await fetch(`/api/v1/spreads/${spreadId}/document/revisions`);const x=await r.json();setRevisions(x.data??[])}
 async function restore(id:string){if(!doc)return;const r=await fetch(`/api/v1/spreads/${spreadId}/document/revisions/${id}/restore`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify({expectedVersion:doc.version})});if(r.ok){const x=await r.json();setDoc(x.data);setHistory([]);setFuture([]);setStatus('Revision restored');setShowHistory(false)}else setStatus(r.status===409?'Conflict—reload required':'Restore failed')}
 useEffect(()=>{function key(e:KeyboardEvent){if(!doc)return;const meta=e.ctrlKey||e.metaKey;if(meta&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();return}if(meta&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(!selected)return;const step=e.shiftKey?10:1;const delta:{[key:string]:[number,number]}={ArrowLeft:[-step,0],ArrowRight:[step,0],ArrowUp:[0,-step],ArrowDown:[0,step]};if(delta[e.key]){e.preventDefault();update(nudgeElement(doc,selected,...delta[e.key]))}if(e.key==='Delete'||e.key==='Backspace'){e.preventDefault();update(removeElement(doc,selected));setSelected(null)}}window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[doc,selected,history,future]);
 const selectedElement=useMemo(()=>doc?.elements.find(e=>e.id===selected),[doc,selected]);
 if(!doc)return <div className={styles.loading}>{status}</div>;
 function addText(){update(addElement(doc!,{id:crypto.randomUUID(),kind:'text',x:24,y:24,width:220,height:80,rotation:0,zIndex:doc!.elements.length,text:'New text frame'}))}
 function addShape(){update(addElement(doc!,{id:crypto.randomUUID(),kind:'shape',x:48,y:48,width:180,height:120,rotation:0,zIndex:doc!.elements.length,fill:'#e5e7eb'}))}
 return <div className={styles.editor}>
  <header className={styles.toolbar}><button onClick={undo} disabled={!history.length}>Undo</button><button onClick={redo} disabled={!future.length}>Redo</button><button onClick={addText}>Text</button><button onClick={addShape}>Shape</button><button onClick={openAssets}>Asset Library</button><button onClick={openHistory}>History</button><label>Zoom <input aria-label="Zoom" type="range" min="25" max="200" step="5" value={zoom} onChange={e=>setZoom(Number(e.target.value))}/>{zoom}%</label><label><input type="checkbox" checked={doc.snapToGrid} onChange={e=>update({...doc,snapToGrid:e.target.checked})}/> Snap</label><span aria-live="polite">{status}</span></header>
  <div className={styles.workspace}><div ref={viewport} className={styles.viewport}><div className={styles.stage} style={{width:doc.widthPt*zoom/100+32,height:doc.heightPt*zoom/100+32}}><Rulers doc={doc} zoom={zoom}/><div className={styles.canvas} style={{width:doc.widthPt,height:doc.heightPt,transform:`scale(${zoom/100})`,backgroundSize:`${doc.gridSizePt}px ${doc.gridSizePt}px`}} onPointerDown={e=>{if(e.target===e.currentTarget)setSelected(null)}}><Guides doc={doc}/>{activeAnnotation?.x!=null&&activeAnnotation?.y!=null&&<button className={styles.annotationPin} style={{left:activeAnnotation.x,top:activeAnnotation.y}} aria-label="Selected annotation">{activeAnnotation.status==='resolved'?'✓':'•'}</button>}{doc.elements.map(el=><EditorElement key={el.id} element={el} doc={doc} selected={selected===el.id} onSelect={()=>setSelected(el.id)} onMove={(x,y)=>update(moveElement(doc,el.id,x,y))} onResize={(h,dx,dy,o)=>update(resizeElement(doc,el.id,h,dx,dy,o))}/>)}</div></div></div>
  <aside className={styles.inspector}><h2>Inspector</h2>{selectedElement?<><label>X <input type="number" value={selectedElement.x} onChange={e=>update(updateElement(doc,selectedElement.id,{x:Number(e.target.value)}))}/></label><label>Y <input type="number" value={selectedElement.y} onChange={e=>update(updateElement(doc,selectedElement.id,{y:Number(e.target.value)}))}/></label><label>Width <input type="number" value={selectedElement.width} onChange={e=>update(updateElement(doc,selectedElement.id,{width:Number(e.target.value)}))}/></label><label>Height <input type="number" value={selectedElement.height} onChange={e=>update(updateElement(doc,selectedElement.id,{height:Number(e.target.value)}))}/></label><label>Rotation <input type="number" value={selectedElement.rotation} onChange={e=>update(updateElement(doc,selectedElement.id,{rotation:Number(e.target.value)}))}/></label><button onClick={()=>{update(removeElement(doc,selectedElement.id));setSelected(null)}}>Delete</button></>:<p>Select an element.</p>}<p>Version {doc.version}</p><p>Arrow keys nudge 1 pt; Shift + arrow nudges 10 pt.</p></aside><ReviewPanel spreadId={spreadId} onSelect={setActiveAnnotation}/></div>
  {showAssets&&<div className={styles.modal} role="dialog" aria-modal="true" aria-label="Asset Library"><div><button className={styles.close} onClick={()=>setShowAssets(false)}>Close</button><h2>Asset Library</h2><div className={styles.assetGrid}>{assets.map(a=><button key={a.id} onClick={()=>{update(placeAsset(doc,{assetId:a.id,assetVersionId:a.current_version_id,src:a.preview_url??'/placeholder-asset.svg'}));setShowAssets(false)}}><img src={a.preview_url??'/placeholder-asset.svg'} alt=""/><span>{a.title??a.filename??'Asset'}</span></button>)}</div></div></div>}
  {showHistory&&<div className={styles.modal} role="dialog" aria-modal="true" aria-label="Revision history"><div><button className={styles.close} onClick={()=>setShowHistory(false)}>Close</button><h2>Revision history</h2>{revisions.length?<ol className={styles.revisions}>{revisions.map(r=><li key={r.id}><div><strong>Version {r.version}</strong><small>{r.changeSummary??'Saved revision'} · {new Date(r.createdAt).toLocaleString()}</small></div><button onClick={()=>restore(r.id)}>Restore</button></li>)}</ol>:<p>No saved revisions yet.</p>}</div></div>}
 </div>}
function Guides({doc}:{doc:SpreadDocument}){const m=24,b=doc.bleedPt;return <><div className={styles.marginGuide} style={{inset:m}}/><div className={styles.bleedGuide} style={{inset:b}}/><div className={styles.centerV}/><div className={styles.centerH}/></>}
function Rulers({doc,zoom}:{doc:SpreadDocument;zoom:number}){const x=Array.from({length:Math.ceil(doc.widthPt/100)+1},(_,i)=>i*100),y=Array.from({length:Math.ceil(doc.heightPt/100)+1},(_,i)=>i*100);return <><div className={styles.rulerX}>{x.map(v=><span key={v} style={{left:v*zoom/100}}>{v}</span>)}</div><div className={styles.rulerY}>{y.map(v=><span key={v} style={{top:v*zoom/100}}>{v}</span>)}</div></>}
function EditorElement({element,doc,selected,onSelect,onMove,onResize}:{element:SpreadElement;doc:SpreadDocument;selected:boolean;onSelect:()=>void;onMove:(x:number,y:number)=>void;onResize:(h:ResizeHandle,dx:number,dy:number,o:SpreadElement)=>void}){const start=useRef<{x:number;y:number;left:number;top:number}|null>(null);return <div role="button" tabIndex={0} aria-label={`${element.kind} element`} className={`${styles.element} ${selected?styles.selected:''}`} style={{left:element.x,top:element.y,width:element.width,height:element.height,transform:`rotate(${element.rotation}deg)`,background:element.kind==='shape'?element.fill:undefined,zIndex:element.zIndex}} onPointerDown={e=>{if((e.target as HTMLElement).dataset.handle)return;onSelect();start.current={x:e.clientX,y:e.clientY,left:element.x,top:element.y};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(start.current)onMove(start.current.left+(e.clientX-start.current.x),start.current.top+(e.clientY-start.current.y))}} onPointerUp={()=>{start.current=null}}>{element.kind==='text'?element.text:element.kind==='image'?<img src={element.src} alt="Placed asset"/>:null}{selected&&handles.map(h=><Resize key={h} handle={h} element={element} onResize={onResize}/>)}</div>}
function Resize({handle,element,onResize}:{handle:ResizeHandle;element:SpreadElement;onResize:(h:ResizeHandle,dx:number,dy:number,o:SpreadElement)=>void}){const start=useRef<{x:number;y:number}|null>(null);return <span data-handle={handle} className={`${styles.handle} ${styles[handle]}`} onPointerDown={e=>{e.stopPropagation();start.current={x:e.clientX,y:e.clientY};e.currentTarget.setPointerCapture(e.pointerId)}} onPointerMove={e=>{if(start.current)onResize(handle,e.clientX-start.current.x,e.clientY-start.current.y,element)}} onPointerUp={()=>{start.current=null}}/>}
