'use client';
import {useMemo,useState} from 'react';
import {Archive,Box,CheckCircle2,FolderPlus,Grid2X2,List,Link2,Search,Tag,Upload,Users,X} from 'lucide-react';
import styles from './AssetLibrary.module.css';
import {demoAssets,demoCollections} from './demo-assets';
import type {Asset,AssetType,ReviewStatus} from './types';
const typeIcon:Record<AssetType,string>={illustration:'🎨',character:'🧍',environment:'🌄',layout:'▦',reference:'🎯',cover:'📕',document:'📄'};
const statuses:ReviewStatus[]=['draft','in_review','changes_requested','approved'];
const types:AssetType[]=['illustration','character','environment','layout','reference','cover','document'];
const label=(value:string)=>value.replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
export function AssetLibrary({bookId}:{bookId:string}){
 const [assets,setAssets]=useState(demoAssets.map(a=>({...a,bookId})));const [query,setQuery]=useState('');const [type,setType]=useState<string>('all');const [status,setStatus]=useState<string>('all');const [collection,setCollection]=useState<string>('all');const [view,setView]=useState<'grid'|'list'>('grid');const [selected,setSelected]=useState<string[]>([]);const [detail,setDetail]=useState<Asset|null>(null);const [uploadOpen,setUploadOpen]=useState(false);const [files,setFiles]=useState<File[]>([]);const [drag,setDrag]=useState(false);const [detailTab,setDetailTab]=useState('metadata');
 const tags=useMemo(()=>Array.from(new Set(assets.flatMap(a=>a.tags))).sort(),[assets]);
 const filtered=useMemo(()=>assets.filter(a=>(!query||`${a.title} ${a.tags.join(' ')} ${a.owner}`.toLowerCase().includes(query.toLowerCase()))&&(type==='all'||a.type===type)&&(status==='all'||a.reviewStatus===status)&&(collection==='all'||a.collectionIds.includes(collection))),[assets,query,type,status,collection]);
 const toggle=(id:string)=>setSelected(s=>s.includes(id)?s.filter(x=>x!==id):[...s,id]);
 const bulk=(op:'archive'|'tag'|'collection')=>{setAssets(items=>items.map(a=>selected.includes(a.id)?op==='archive'?{...a,lifecycleStatus:'archived'}:op==='tag'?{...a,tags:Array.from(new Set([...a.tags,'priority']))}:{...a,collectionIds:Array.from(new Set([...a.collectionIds,'publishing']))}:a));setSelected([])};
 const addUploads=()=>{if(!files.length)return;const created=files.map((file,i):Asset=>{const id=`asset-${Date.now()}-${i}`;const v={id:`${id}-v1`,version:1,filename:file.name,mimeType:file.type||'application/octet-stream',sizeBytes:file.size,storagePath:`books/${bookId}/assets/${id}/v1/${file.name}`,createdAt:new Date().toISOString(),createdBy:'Current user',reviewStatus:'draft' as const,isCurrent:true};return{id,bookId,title:file.name.replace(/\.[^.]+$/,''),type:'illustration',tags:['new-upload'],collectionIds:[],owner:'Current user',createdAt:v.createdAt,updatedAt:v.createdAt,reviewStatus:'draft',lifecycleStatus:'active',currentVersion:v,versions:[v],usage:[],relationships:[]}});setAssets(a=>[...created,...a]);setFiles([]);setUploadOpen(false)};
 return <div className={styles.library}>
  <div className={styles.summary}><div className={styles.metric}><strong>{assets.length}</strong><span>Total assets</span></div><div className={styles.metric}><strong>{assets.filter(a=>a.reviewStatus==='in_review').length}</strong><span>In review</span></div><div className={styles.metric}><strong>{assets.filter(a=>a.reviewStatus==='approved').length}</strong><span>Approved</span></div><div className={styles.metric}><strong>{assets.reduce((n,a)=>n+a.usage.length,0)}</strong><span>Tracked usages</span></div></div>
  <div className={styles.collectionStrip}>{demoCollections.map(c=><button className={styles.collection} key={c.id} onClick={()=>setCollection(c.id)}><strong>{c.name}</strong><span>{c.assetCount} assets · {c.description}</span></button>)}</div>
  <div className={styles.toolbar}><div className={styles.search}><Search size={16}/> <input aria-label="Search assets" value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search assets, tags or owners…" style={{border:0,background:'transparent',outline:'none',width:'90%'}}/></div><select className={styles.select} value={type} onChange={e=>setType(e.target.value)}><option value="all">All types</option>{types.map(t=><option key={t} value={t}>{label(t)}</option>)}</select><select className={styles.select} value={status} onChange={e=>setStatus(e.target.value)}><option value="all">All review states</option>{statuses.map(s=><option key={s} value={s}>{label(s)}</option>)}</select><div className={styles.viewToggle}><button data-active={view==='grid'} onClick={()=>setView('grid')} aria-label="Grid view"><Grid2X2 size={17}/></button><button data-active={view==='list'} onClick={()=>setView('list')} aria-label="List view"><List size={17}/></button></div><button className="button buttonPrimary" onClick={()=>setUploadOpen(true)}><Upload size={16}/> Upload</button></div>
  <div className={styles.layout}><aside className={styles.facets}><div className={styles.facetGroup}><h4>Collections</h4><label className={styles.check}><input type="radio" checked={collection==='all'} onChange={()=>setCollection('all')}/> All assets</label>{demoCollections.map(c=><label className={styles.check} key={c.id}><input type="radio" checked={collection===c.id} onChange={()=>setCollection(c.id)}/>{c.name}</label>)}</div><div className={styles.facetGroup}><h4>Popular tags</h4>{tags.slice(0,8).map(t=><button key={t} className={styles.check} onClick={()=>setQuery(t)}><Tag size={13}/>{t}</button>)}</div><div className={styles.facetGroup}><h4>Lifecycle</h4><label className={styles.check}><Archive size={13}/> Active storage</label><label className={styles.check}><Box size={13}/> Archive</label></div></aside>
   <main>{view==='grid'?<div className={styles.grid}>{filtered.map(a=><article key={a.id} className={styles.assetCard} data-selected={selected.includes(a.id)}><div className={styles.thumb} onDoubleClick={()=>setDetail(a)}><input aria-label={`Select ${a.title}`} type="checkbox" checked={selected.includes(a.id)} onChange={()=>toggle(a.id)}/><span>{typeIcon[a.type]}</span><span className={styles.version}>v{a.currentVersion.version}</span></div><div className={styles.cardBody} onClick={()=>setDetail(a)}><h3>{a.title}</h3><div className={styles.meta}><span>{label(a.type)}</span><span className={`badge ${a.reviewStatus==='approved'?'success':a.reviewStatus==='changes_requested'?'danger':a.reviewStatus==='in_review'?'warning':''}`}>{label(a.reviewStatus)}</span></div><div className={styles.tags}>{a.tags.slice(0,3).map(t=><span className={styles.tag} key={t}>{t}</span>)}</div></div></article>)}</div>:<div className={styles.list}><table><thead><tr><th></th><th>Asset</th><th>Type</th><th>Version</th><th>Review</th><th>Owner</th><th>Usage</th><th>Updated</th></tr></thead><tbody>{filtered.map(a=><tr key={a.id} className={styles.clickable} onDoubleClick={()=>setDetail(a)}><td><input type="checkbox" checked={selected.includes(a.id)} onChange={()=>toggle(a.id)}/></td><td><strong>{a.title}</strong></td><td>{label(a.type)}</td><td>v{a.currentVersion.version}</td><td>{label(a.reviewStatus)}</td><td>{a.owner}</td><td>{a.usage.length}</td><td>{new Date(a.updatedAt).toLocaleDateString()}</td></tr>)}</tbody></table></div>}{filtered.length===0&&<div className="empty"><h3>No matching assets</h3><p className="muted">Adjust the filters or upload a new production asset.</p></div>}</main></div>
  {selected.length>0&&<div className={styles.bulkBar}><span>{selected.length} selected</span><button className="button" onClick={()=>bulk('tag')}><Tag size={15}/> Add “priority” tag</button><button className="button" onClick={()=>bulk('collection')}><FolderPlus size={15}/> Add to publishing</button><button className="button" onClick={()=>bulk('archive')}><Archive size={15}/> Archive</button><button className="iconButton" onClick={()=>setSelected([])}><X size={16}/></button></div>}
  {detail&&<div className={styles.drawerBackdrop} onMouseDown={()=>setDetail(null)}><section className={styles.drawer} onMouseDown={e=>e.stopPropagation()}><div className={styles.drawerHeader}><div><span className="badge">{label(detail.type)}</span><h2>{detail.title}</h2><p className="muted">Current version v{detail.currentVersion.version} · {label(detail.reviewStatus)}</p></div><button className="iconButton" onClick={()=>setDetail(null)}><X/></button></div><div className={styles.tabs}>{['metadata','versions','usage','relationships','lifecycle'].map(t=><button key={t} data-active={detailTab===t} onClick={()=>setDetailTab(t)}>{label(t)}</button>)}</div>{detailTab==='metadata'&&<div className={styles.detailGrid}><div className={styles.field}><label>Title</label><input defaultValue={detail.title}/></div><div className={styles.field}><label>Asset type</label><select defaultValue={detail.type}>{types.map(t=><option key={t}>{t}</option>)}</select></div><div className={styles.field} style={{gridColumn:'1/-1'}}><label>Description</label><textarea defaultValue={detail.description}/></div><div className={styles.field} style={{gridColumn:'1/-1'}}><label>Tags</label><input defaultValue={detail.tags.join(', ')}/></div><button className="button buttonPrimary">Save metadata</button></div>}{detailTab==='versions'&&<div className={styles.timeline}>{[...detail.versions].reverse().map(v=><div className={styles.timelineItem} key={v.id}><strong>Version {v.version} {v.isCurrent&&<span className="badge success">Current</span>}</strong><p className="muted">{v.filename} · {(v.sizeBytes/1024).toFixed(0)} KB · {v.createdBy}</p><span className="badge">{label(v.reviewStatus)}</span></div>)}</div>}{detailTab==='usage'&&<div className={styles.timeline}>{detail.usage.map(u=><div className={styles.timelineItem} key={u.id}><strong>{u.label}</strong><p className="muted">{u.usageRole} · {label(u.contextType)}</p></div>)}{!detail.usage.length&&<p className="muted">This asset is not currently used.</p>}</div>}{detailTab==='relationships'&&<div><p className="muted">Connect variants, derivatives, references, and companion assets.</p><button className="button"><Link2 size={16}/> Add relationship</button></div>}{detailTab==='lifecycle'&&<div><p><strong>Storage state:</strong> {label(detail.lifecycleStatus)}</p><p className="muted">Current versions remain in active storage. Superseded originals can transition to cold storage according to book policy.</p><button className="button"><Archive size={16}/> Archive asset</button></div>}</section></div>}
  {uploadOpen&&<div className={styles.modalBackdrop} onMouseDown={()=>setUploadOpen(false)}><section className={styles.modal} onMouseDown={e=>e.stopPropagation()}><div className={styles.drawerHeader}><div><h2>Upload assets</h2><p className="muted">Files become immutable Version 1 records after storage finalisation.</p></div><button className="iconButton" onClick={()=>setUploadOpen(false)}><X/></button></div><label className={styles.dropzone} data-drag={drag} onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);setFiles(Array.from(e.dataTransfer.files))}}><Upload size={28}/><h3>Drop production files here</h3><p className="muted">SVG, PNG, JPEG, PSD, TIFF, PDF and packaged source files</p><input type="file" multiple hidden onChange={e=>setFiles(Array.from(e.target.files||[]))}/><span className="button">Choose files</span></label><div className={styles.uploadList}>{files.map(f=><div className={styles.uploadItem} key={`${f.name}-${f.size}`}><span><strong>{f.name}</strong><br/><small className="muted">{(f.size/1024/1024).toFixed(2)} MB</small></span><CheckCircle2 size={18}/></div>)}</div><div className={styles.modalActions}><button className="button" onClick={()=>setUploadOpen(false)}>Cancel</button><button className="button buttonPrimary" disabled={!files.length} onClick={addUploads}><Upload size={16}/> Create {files.length||''} asset{files.length===1?'':'s'}</button></div></section></div>}
 </div>
}
