import {adminDb} from '@/lib/spread-manager-server';
import {requirePermission} from '@/lib/rbac/service';
import type {SessionIdentity} from '@studio-os/auth';
import type {AnnotationStatus,ReviewCycle,SpreadAnnotation} from './types';
const db=()=>adminDb();
export async function listReviews(identity:SessionIdentity,spreadId:string){await requirePermission(identity,'reviews.read');const [cycles,annotations]=await Promise.all([
 db().from('review_cycles').select('*').eq('organisation_id',identity.organisationId).eq('spread_id',spreadId).order('round_number',{ascending:false}),
 db().from('spread_annotations').select('*,review_comments(*)').eq('organisation_id',identity.organisationId).eq('spread_id',spreadId).order('created_at',{ascending:false})]);
 if(cycles.error||annotations.error)throw cycles.error??annotations.error;
 return {cycles:(cycles.data??[]).map((r:any):ReviewCycle=>({id:r.id,spreadId:r.spread_id,title:r.title,roundNumber:r.round_number,status:r.status,dueAt:r.due_at,createdAt:r.created_at})),annotations:(annotations.data??[]).map((r:any):SpreadAnnotation=>({id:r.id,spreadId:r.spread_id,reviewCycleId:r.review_cycle_id,elementId:r.element_id,annotationType:r.annotation_type,x:r.x==null?null:Number(r.x),y:r.y==null?null:Number(r.y),width:r.width==null?null:Number(r.width),height:r.height==null?null:Number(r.height),status:r.status,createdBy:r.created_by,createdAt:r.created_at,comments:(r.review_comments??[]).map((c:any)=>({id:c.id,annotationId:c.annotation_id,parentCommentId:c.parent_comment_id,body:c.body,mentions:c.mentions??[],createdBy:c.created_by,createdAt:c.created_at}))}))};
}
export async function createCycle(identity:SessionIdentity,spreadId:string,input:{title:string;dueAt?:string},requestId:string){await requirePermission(identity,'reviews.create');const result=await db().from('review_cycles').insert({organisation_id:identity.organisationId,spread_id:spreadId,title:input.title,due_at:input.dueAt??null,created_by:identity.userId}).select('*').single();if(result.error)throw result.error;await emit(identity,requestId,'review.created','review_cycle',result.data.id,{spreadId});return result.data}
export async function createAnnotation(identity:SessionIdentity,spreadId:string,input:{reviewCycleId?:string;elementId?:string;annotationType:string;x?:number;y?:number;width?:number;height?:number;body:string;mentions?:string[]},requestId:string){await requirePermission(identity,'annotations.create');const database=db();const created=await database.from('spread_annotations').insert({organisation_id:identity.organisationId,spread_id:spreadId,review_cycle_id:input.reviewCycleId??null,element_id:input.elementId??null,annotation_type:input.annotationType,x:input.x??null,y:input.y??null,width:input.width??null,height:input.height??null,created_by:identity.userId}).select('*').single();if(created.error)throw created.error;const comment=await database.from('review_comments').insert({organisation_id:identity.organisationId,annotation_id:created.data.id,body:input.body,mentions:input.mentions??[],created_by:identity.userId}).select('*').single();if(comment.error)throw comment.error;await emit(identity,requestId,'annotation.created','spread_annotation',created.data.id,{spreadId});return {annotation:created.data,comment:comment.data}}
export async function addComment(identity:SessionIdentity,annotationId:string,input:{body:string;parentCommentId?:string;mentions?:string[]},requestId:string){await requirePermission(identity,'reviews.comment');const result=await db().from('review_comments').insert({organisation_id:identity.organisationId,annotation_id:annotationId,parent_comment_id:input.parentCommentId??null,body:input.body,mentions:input.mentions??[],created_by:identity.userId}).select('*').single();if(result.error)throw result.error;await emit(identity,requestId,'comment.created','review_comment',result.data.id,{annotationId,mentions:input.mentions??[]});return result.data}
export async function setAnnotationStatus(identity:SessionIdentity,annotationId:string,status:AnnotationStatus,requestId:string){await requirePermission(identity,'reviews.resolve');const result=await db().rpc('resolve_spread_annotation',{p_annotation_id:annotationId,p_organisation_id:identity.organisationId,p_user_id:identity.userId,p_status:status});if(result.error)throw result.error;await emit(identity,requestId,`comment.${status}`,'spread_annotation',annotationId,{status});return result.data?.[0]}
async function emit(identity:SessionIdentity,requestId:string,action:string,resourceType:string,resourceId:string,metadata:Record<string,unknown>){const database=db();await Promise.all([database.from('platform_audit_events').insert({organisation_id:identity.organisationId,request_id:requestId,actor_id:identity.userId,action,resource_type:resourceType,resource_id:resourceId,metadata}),database.from('platform_event_outbox').insert({organisation_id:identity.organisationId,event_type:action,aggregate_type:resourceType,aggregate_id:resourceId,payload:metadata})])}
