import type {DashboardData, DashboardKind} from './types';
const months=['Feb','Mar','Apr','May','Jun','Jul'];
const data: Record<DashboardKind,DashboardData>={
production:{kind:'production',title:'Production dashboard',description:'Book and spread progress across the active production portfolio.',metrics:[{label:'Books on track',value:'8 / 10',change:'+1 this month',tone:'positive'},{label:'Spreads complete',value:'72%',change:'+9 pts',tone:'positive'},{label:'At risk',value:'14',change:'3 critical',tone:'warning'},{label:'Forecast delivery',value:'18 Aug',tone:'neutral'}],trend:months.map((label,i)=>({label,value:[42,48,55,61,67,72][i],secondary:[45,50,56,62,68,75][i]})),breakdown:[{label:'Complete',value:72},{label:'In review',value:14},{label:'In progress',value:10},{label:'Blocked',value:4}],rows:[{Book:'Meet Mia',Progress:'78%',Status:'On track',Due:'18 Aug 2026'},{Book:'The Forest Club',Progress:'64%',Status:'At risk',Due:'29 Aug 2026'},{Book:'Numbers at Play',Progress:'86%',Status:'On track',Due:'8 Aug 2026'}]},
team:{kind:'team',title:'Team dashboard',description:'Delivery, quality, and collaboration signals by team.',metrics:[{label:'Active contributors',value:'24',change:'+3',tone:'positive'},{label:'Tasks completed',value:'186',change:'+12%',tone:'positive'},{label:'Overdue tasks',value:'11',change:'-4',tone:'positive'},{label:'Collaboration score',value:'91%',tone:'neutral'}],trend:months.map((label,i)=>({label,value:[126,139,148,155,174,186][i],secondary:[18,16,17,14,15,11][i]})),breakdown:[{label:'Illustration',value:88},{label:'Editorial',value:93},{label:'Design',value:84},{label:'Production',value:90}],rows:[{Team:'Editorial',Members:7,Completed:72,Overdue:2},{Team:'Illustration',Members:9,Completed:61,Overdue:5},{Team:'Production',Members:5,Completed:38,Overdue:3},{Team:'Design',Members:3,Completed:15,Overdue:1}]},
review:{kind:'review',title:'Review dashboard',description:'Review volume, turnaround, outcomes, and required-change trends.',metrics:[{label:'Median turnaround',value:'18h',change:'-5h',tone:'positive'},{label:'Open reviews',value:'23',change:'6 due today',tone:'warning'},{label:'First-pass approval',value:'68%',change:'+4 pts',tone:'positive'},{label:'Required changes',value:'31',change:'-8%',tone:'positive'}],trend:months.map((label,i)=>({label,value:[31,29,26,25,21,18][i],secondary:[54,58,61,63,65,68][i]})),breakdown:[{label:'Approved',value:68},{label:'Changes requested',value:22},{label:'In review',value:8},{label:'Cancelled',value:2}],rows:[{Reviewer:'A. Mokoena',Assigned:18,Completed:16,'Median hours':14},{Reviewer:'J. Smith',Assigned:15,Completed:13,'Median hours':19},{Reviewer:'L. Daniels',Assigned:12,Completed:12,'Median hours':16}]},
workload:{kind:'workload',title:'Workload dashboard',description:'Capacity, allocation, and delivery pressure across contributors.',metrics:[{label:'Capacity used',value:'82%',change:'+3 pts',tone:'warning'},{label:'Overallocated',value:'4',change:'2 critical',tone:'warning'},{label:'Available capacity',value:'126h',tone:'neutral'},{label:'Due this week',value:'47',change:'-6',tone:'positive'}],trend:months.map((label,i)=>({label,value:[71,74,77,79,80,82][i],secondary:[29,26,23,21,20,18][i]})),breakdown:[{label:'A. Mokoena',value:96},{label:'J. Smith',value:91},{label:'L. Daniels',value:84},{label:'N. Dlamini',value:76},{label:'T. Naidoo',value:63}],rows:[{Contributor:'A. Mokoena',Role:'Editor',Allocation:'96%',Tasks:17},{Contributor:'J. Smith',Role:'Illustrator',Allocation:'91%',Tasks:14},{Contributor:'L. Daniels',Role:'Designer',Allocation:'84%',Tasks:11},{Contributor:'N. Dlamini',Role:'Producer',Allocation:'76%',Tasks:9}]},
executive:{kind:'executive',title:'Executive dashboard',description:'Portfolio health, delivery confidence, quality, and operational performance.',metrics:[{label:'Portfolio completion',value:'74%',change:'+8 pts',tone:'positive'},{label:'On-time forecast',value:'87%',change:'+2 pts',tone:'positive'},{label:'Approval rate',value:'81%',change:'+5 pts',tone:'positive'},{label:'Cost variance',value:'-1.8%',tone:'positive'}],trend:months.map((label,i)=>({label,value:[58,61,65,68,71,74][i],secondary:[80,82,83,84,85,87][i]})),breakdown:[{label:'On track',value:8},{label:'At risk',value:2},{label:'Delayed',value:1}],rows:[{Portfolio:'Children’s books',Completion:'76%',Confidence:'High',Variance:'-2.1%'},{Portfolio:'Learning resources',Completion:'70%',Confidence:'Medium',Variance:'+0.8%'},{Portfolio:'Digital editions',Completion:'81%',Confidence:'High',Variance:'-1.4%'}]}
};
export const getDemoDashboard=(kind:DashboardKind)=>data[kind];
