'use client';
import {useEffect,useMemo,useState} from 'react';
import styles from './ReportsDashboard.module.css';
import type {DashboardData,DashboardKind,DateRange} from './types';
import {getDemoDashboard} from './demo-reports';
import {downloadCsv} from './export';
import {saveSchedule} from './report-service';
const kinds:DashboardKind[]=['production','team','review','workload','executive'];
export function ReportsDashboard({bookId}:{bookId?:string}){
 const [kind,setKind]=useState<DashboardKind>('production');const [range,setRange]=useState<DateRange>('6m');const [team,setTeam]=useState('all');const [data,setData]=useState<DashboardData>(()=>getDemoDashboard('production'));const [scheduling,setScheduling]=useState(false);const [notice,setNotice]=useState('');
 useEffect(()=>{setData(getDemoDashboard(kind))},[kind,range,team,bookId]);
 const max=useMemo(()=>Math.max(...data.trend.flatMap(x=>[x.value,x.secondary??0]),1),[data]);
 const pdfUrl=`/api/reports/export?kind=${kind}&format=pdf${bookId?`&bookId=${bookId}`:''}`;
 async function submitSchedule(formData:FormData){await saveSchedule({name:String(formData.get('name')),dashboard:kind,cadence:String(formData.get('cadence')) as 'daily'|'weekly'|'monthly',deliveryTime:String(formData.get('time')),recipients:String(formData.get('recipients')).split(',').map(x=>x.trim()).filter(Boolean),format:String(formData.get('format')) as 'csv'|'pdf',enabled:true});setScheduling(false);setNotice('Scheduled report saved.');}
 return <div className={styles.shell}>
  <div className={styles.tabs} aria-label="Dashboards">{kinds.map(item=><button key={item} className={`${styles.tab} ${kind===item?styles.active:''}`} onClick={()=>setKind(item)}>{item[0].toUpperCase()+item.slice(1)}</button>)}</div>
  <div className={styles.toolbar}><div className={styles.field}><label htmlFor="range">Date range</label><select id="range" value={range} onChange={e=>setRange(e.target.value as DateRange)}><option value="30d">Last 30 days</option><option value="90d">Last 90 days</option><option value="6m">Last 6 months</option><option value="12m">Last 12 months</option></select></div><div className={styles.field}><label htmlFor="team">Team</label><select id="team" value={team} onChange={e=>setTeam(e.target.value)}><option value="all">All teams</option><option>Editorial</option><option>Illustration</option><option>Production</option></select></div><div className={styles.actions}><button className="button" onClick={()=>downloadCsv(data)}>Export CSV</button><a className="button" href={pdfUrl}>Export PDF</a><button className="button buttonPrimary" onClick={()=>setScheduling(true)}>Schedule</button></div></div>
  {notice&&<div className="notice" role="status">{notice}</div>}
  <header><h2>{data.title}</h2><p className="muted">{data.description}</p></header>
  <div className={styles.metrics}>{data.metrics.map(m=><div className={styles.metric} key={m.label}><span className="muted">{m.label}</span><strong>{m.value}</strong>{m.change&&<small className={m.tone==='positive'?styles.positive:m.tone==='warning'?styles.warning:''}>{m.change}</small>}</div>)}</div>
  <div className={styles.charts}><section className={styles.panel}><h3>Trend</h3><div className={styles.chart} role="img" aria-label={`${data.title} trend chart`}>{data.trend.map(point=><div className={styles.barGroup} key={point.label}><span className={styles.bar} style={{height:`${point.value/max*100}%`}} title={`${point.label}: ${point.value}`}/>{point.secondary!==undefined&&<span className={`${styles.bar} ${styles.secondary}`} style={{height:`${point.secondary/max*100}%`}} title={`${point.label}: ${point.secondary}`}/>}<span className={styles.barLabel}>{point.label}</span></div>)}</div></section><section className={styles.panel}><h3>Breakdown</h3><div className={styles.breakdown}>{data.breakdown.map(item=><div key={item.label}><div className={styles.rowLabel}><span>{item.label}</span><strong>{item.value}</strong></div><div className={styles.track}><div className={styles.fill} style={{width:`${Math.min(item.value,100)}%`}}/></div></div>)}</div></section></div>
  <section className={styles.panel}><h3>Details</h3><div className={styles.tableWrap}><table className={styles.table}><thead><tr>{Object.keys(data.rows[0]??{}).map(h=><th key={h}>{h}</th>)}</tr></thead><tbody>{data.rows.map((row,i)=><tr key={i}>{Object.keys(data.rows[0]??{}).map(h=><td key={h}>{row[h]}</td>)}</tr>)}</tbody></table></div></section>
  {scheduling&&<div className={styles.modalBackdrop} onMouseDown={e=>e.target===e.currentTarget&&setScheduling(false)}><form className={styles.modal} action={submitSchedule}><h2>Schedule {kind} report</h2><div className={styles.field}><label htmlFor="schedule-name">Name</label><input id="schedule-name" name="name" required defaultValue={`${data.title} digest`}/></div><div className={styles.field}><label htmlFor="cadence">Cadence</label><select id="cadence" name="cadence"><option value="daily">Daily</option><option value="weekly">Weekly</option><option value="monthly">Monthly</option></select></div><div className={styles.field}><label htmlFor="time">Delivery time</label><input id="time" name="time" type="time" defaultValue="08:00"/></div><div className={styles.field}><label htmlFor="recipients">Recipients</label><input id="recipients" name="recipients" type="text" placeholder="editor@example.com, producer@example.com" required/></div><div className={styles.field}><label htmlFor="format">Format</label><select id="format" name="format"><option value="pdf">PDF</option><option value="csv">CSV</option></select></div><div className={styles.actions}><button type="button" className="button" onClick={()=>setScheduling(false)}>Cancel</button><button className="button buttonPrimary">Save schedule</button></div></form></div>}
 </div>
}
