'use client';
import {useEffect,useMemo,useState} from 'react';
type Role={id:string;code:string;name:string;description?:string;is_system?:boolean};type Permission={code:string;description:string};type Grant={role_id:string;permission_code:string};
export function PermissionMatrix(){const [roles,setRoles]=useState<Role[]>([]),[permissions,setPermissions]=useState<Permission[]>([]),[grants,setGrants]=useState<Grant[]>([]),[saving,setSaving]=useState<string|null>(null),[error,setError]=useState('');
 useEffect(()=>{fetch('/api/v1/rbac/permissions').then(r=>r.json()).then(j=>{setRoles(j.data?.roles??[]);setPermissions(j.data?.permissions??[]);setGrants(j.data?.grants??[])}).catch(()=>setError('Unable to load permissions'))},[]);
 const grouped=useMemo(()=>permissions.reduce<Record<string,Permission[]>>((a,p)=>{const group=p.code.split('.')[0];(a[group]??=[]).push(p);return a},{}),[permissions]);
 const checked=(roleId:string,code:string)=>grants.some(g=>g.role_id===roleId&&g.permission_code===code);
 async function toggle(roleId:string,code:string){const next=checked(roleId,code)?grants.filter(g=>!(g.role_id===roleId&&g.permission_code===code)):[...grants,{role_id:roleId,permission_code:code}];setGrants(next);setSaving(roleId);setError('');const codes=next.filter(g=>g.role_id===roleId).map(g=>g.permission_code);const res=await fetch(`/api/v1/rbac/roles/${roleId}/permissions`,{method:'PUT',headers:{'content-type':'application/json'},body:JSON.stringify({permissions:codes})});if(!res.ok)setError('Permission update failed. Refresh and try again.');setSaving(null)}
 return <div className="card"><div className="pageHeader"><div><h2>Permission matrix</h2><p>Grant least-privilege capabilities to each role.</p></div>{saving&&<span>Saving…</span>}</div>{error&&<div role="alert" className="errorState">{error}</div>}<div style={{overflowX:'auto'}}><table className="dataTable"><thead><tr><th>Permission</th>{roles.map(r=><th key={r.id}>{r.name}</th>)}</tr></thead><tbody>{Object.entries(grouped).flatMap(([group,items])=>[<tr key={`${group}-heading`}><th colSpan={roles.length+1}>{group}</th></tr>,...items.map(permission=><tr key={permission.code}><td><strong>{permission.code}</strong><div>{permission.description}</div></td>{roles.map(role=><td key={role.id}><input aria-label={`${role.name}: ${permission.code}`} type="checkbox" checked={checked(role.id,permission.code)} disabled={Boolean(role.is_system)} onChange={()=>toggle(role.id,permission.code)}/></td>)}</tr>)])}</tbody></table></div></div>}
